### PR TITLE
Draft - Create security_report.md

### PR DESCRIPTION
**Pull request by DonRichards**
Waiting on comments by from Isabella before merging.

### CODE REVIEW

**Comment by ysuarez** [comment]
Couple of things. Can someone assign this issue to me to help me track it? I will create a PR that will make an issue template choice that is just a link, that then links to a wiki page instead of creating a new issue. @inikolaidis can you assign this to me?

**Comment by DonRichards** [comment]
Pointer could be pointed to https://github.com/Islandora/islandora-community/wiki/security 🤷

**Comment by ysuarez** [comment]
I finally did some research on this and discovered the preferred Github way to approach security policies, but my original approach can be used for other links. I will have a new PR in a couple of days.

**Comment by ysuarez** [comment]
I just created PR #3 with my attempt to achieve what Don wanted to achieve. The content I created may need editing. This was just a first attempt.

**Comment by seth-shaw-asu** [comment]
Superseded by #3

**Pull request closed without merging**
